[project]
dependencies = [
  "numpy~=2.2.3",
  "matplotlib~=3.10.0",
  "requests~=2.32.3",
  "bleach~=6.2.0",
  "gitpython~=3.1.44",
]
license = "GPL-3.0-or-later"
name = "gamepack"
version = "0.2.3"
description = "factored out game related stuff from NossiNet"
authors = [{ name = "Maric", email = "x4dr@hotmail.com" }]
readme = "README.md"
keywords = ["game", "package"]
classifiers = [
  "Development Status :: 2 - Pre-Alpha",
  "Intended Audience :: Internal",
  "Operating System :: POSIX :: Linux",
  "Programming Language :: Python :: 3.12",
]

[tool.bumpversion]
current_version = "0.2.3"
commit = true
tag = true

[[tool.bumpversion.files]]
filename = "pyproject.toml"

[tool.setuptools]
packages = ["gamepack"]
